/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.vbms.autopilot.gui;

import dev.vbms.autopilot.sim.cad.GameView;
import javax.swing.JPanel;

/**
 *
 * @author pcmobile
 */
public class GamePanel extends JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel () {
        initComponents();
    }
    
    public void initViews () {
        jMonkeyPanel1.run(new GameView());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonkeyPanel1 = new dev.vbms.autopilot.gui.JMonkeyPanel();

        org.jdesktop.layout.GroupLayout jMonkeyPanel1Layout = new org.jdesktop.layout.GroupLayout(jMonkeyPanel1);
        jMonkeyPanel1.setLayout(jMonkeyPanel1Layout);
        jMonkeyPanel1Layout.setHorizontalGroup(
            jMonkeyPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jMonkeyPanel1Layout.setVerticalGroup(
            jMonkeyPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jMonkeyPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jMonkeyPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dev.vbms.autopilot.gui.JMonkeyPanel jMonkeyPanel1;
    // End of variables declaration//GEN-END:variables
}
