package dev.vbms.autopilot.gui;

import com.jme3.app.Application;
import com.jme3.system.AppSettings;
import com.jme3.system.JmeCanvasContext;
import java.awt.Dimension;
import java.awt.FlowLayout;

public class JMonkeyPanel extends javax.swing.JPanel {
    
    int width = 400;
    int height = 400;
    
    public void run (Application main) {
        // create new JME appsettings
        AppSettings settings = new AppSettings(true);
        settings.setWidth(width);
        settings.setHeight(height);
        // create new canvas application
        main.setSettings(settings);
        main.createCanvas();
        JmeCanvasContext ctx = (JmeCanvasContext) main.getContext();
        ctx.setSystemListener(main);
        Dimension dim = new Dimension(width, height);
        ctx.getCanvas().setPreferredSize(dim);
        setLayout(new FlowLayout());
        add(ctx.getCanvas());
        // start the application
        main.startCanvas();
    }

    /**
     * Creates new form JMonkeyPanel
     */
    public JMonkeyPanel() {
        // initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
